const items = [
    {
        "_id": "5cebc9df33bb853b5cfaa04d",
        "order": "Где вы живете?",
        "text": "Квартира",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "type_of_accommodation",
        "kind": "Radio",
        "position": 1,
        "__v": 0
    },
    {
        "_id": "5cebca0233bb853b5cfaa04e",
        "order": "Где вы живете?",
        "text": "Свой дом",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "type_of_accommodation",
        "kind": "Radio",
        "position": 2,
        "__v": 0
    },
    {
        "_id": "5cebca4633bb853b5cfaa04f",
        "order": "Где вы живете?",
        "text": "1 комнатная",
        "icon": "",
        "price": 5000,
        "discount": 0,
        "name": "number_of_rooms",
        "kind": "Choice",
        "position": 1,
        "__v": 0
    },
    {
        "_id": "5cebca5c33bb853b5cfaa050",
        "order": "Где вы живете?",
        "text": "2-х комнатная",
        "icon": "",
        "price": 5000,
        "discount": 0,
        "name": "number_of_rooms",
        "kind": "Choice",
        "position": 2,
        "__v": 0
    },
    {
        "_id": "5cebca6133bb853b5cfaa051",
        "order": "Где вы живете?",
        "text": "3-х комнатная",
        "icon": "",
        "price": 5000,
        "discount": 0,
        "name": "number_of_rooms",
        "kind": "Choice",
        "position": 3,
        "__v": 0
    },
    {
        "_id": "5cebca6a33bb853b5cfaa052",
        "order": "Где вы живете?",
        "text": "4-х комнатная",
        "icon": "",
        "price": 5000,
        "discount": 0,
        "name": "number_of_rooms",
        "kind": "Choice",
        "position": 4,
        "__v": 0
    },
    {
        "_id": "5cebca7333bb853b5cfaa053",
        "order": "Где вы живете?",
        "text": "5-х комнатная",
        "icon": "",
        "price": 5000,
        "discount": 0,
        "name": "number_of_rooms",
        "kind": "Choice",
        "position": 5,
        "__v": 0
    },
    {
        "_id": "5cebca8f33bb853b5cfaa054",
        "order": "Где вы живете?",
        "text": "1 санузла",
        "icon": "",
        "price": 5000,
        "discount": 0,
        "name": "number_of_bathrooms",
        "kind": "Choice",
        "position": 1,
        "__v": 0
    },
    {
        "_id": "5cebca9933bb853b5cfaa056",
        "order": "Где вы живете?",
        "text": "2 санузла",
        "icon": "",
        "price": 5000,
        "discount": 0,
        "name": "number_of_bathrooms",
        "kind": "Choice",
        "position": 2,
        "__v": 0
    },
    {
        "_id": "5cebca9f33bb853b5cfaa057",
        "order": "Где вы живете?",
        "text": "3 санузла",
        "icon": "",
        "price": 5000,
        "discount": 0,
        "name": "number_of_bathrooms",
        "kind": "Choice",
        "position": 3,
        "__v": 0
    },
    {
        "_id": "5cebcaa433bb853b5cfaa058",
        "order": "Где вы живете?",
        "text": "4 санузла",
        "icon": "",
        "price": 5000,
        "discount": 0,
        "name": "number_of_bathrooms",
        "kind": "Choice",
        "position": 4,
        "__v": 0
    },
    {
        "_id": "5cebcaaa33bb853b5cfaa059",
        "order": "Где вы живете?",
        "text": "5 санузла",
        "icon": "",
        "price": 5000,
        "discount": 0,
        "name": "number_of_bathrooms",
        "kind": "Choice",
        "position": 5,
        "__v": 0
    },
    {
        "_id": "5cebcb2533bb853b5cfaa05a",
        "order": "Тип уборки",
        "text": "Стандартная уборка",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "cleaning_type",
        "kind": "Radio",
        "position": 1,
        "__v": 0
    },
    {
        "_id": "5cebcb3533bb853b5cfaa05b",
        "order": "Тип уборки",
        "text": "Генеральная уборка",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "cleaning_type",
        "kind": "Radio",
        "position": 2,
        "__v": 0
    },
    {
        "_id": "5cebcb4c33bb853b5cfaa05c",
        "order": "Тип уборки",
        "text": "Уборка после ремонта",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "cleaning_type",
        "kind": "Radio",
        "position": 3,
        "__v": 0
    },
    {
        "_id": "5cebcb5733bb853b5cfaa05d",
        "order": "Тип уборки",
        "text": "Экспресс уборка",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "cleaning_type",
        "kind": "Radio",
        "position": 4,
        "__v": 0
    },
    {
        "_id": "5cebcb8f33bb853b5cfaa05e",
        "order": "Как часто нам убираться у Вас?",
        "text": "Каждый месяц",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "cleaning_time",
        "kind": "Radio",
        "position": 1,
        "__v": 0
    },
    {
        "_id": "5cebcbac33bb853b5cfaa05f",
        "order": "Как часто нам убираться у Вас?",
        "text": "Каждую неделю",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "cleaning_time",
        "kind": "Radio",
        "position": 2,
        "__v": 0
    },
    {
        "_id": "5cebcbb933bb853b5cfaa060",
        "order": "Как часто нам убираться у Вас?",
        "text": "Каждый божий день",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "cleaning_time",
        "kind": "Radio",
        "position": 3,
        "__v": 0
    },
    {
        "_id": "5cebcbc233bb853b5cfaa061",
        "order": "Как часто нам убираться у Вас?",
        "text": "Разовая уборка",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "cleaning_time",
        "kind": "Radio",
        "position": 4,
        "__v": 0
    },
    {
        "_id": "5cebcc0633bb853b5cfaa062",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Холодильник",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 1,
        "__v": 0
    },
    {
        "_id": "5cebcc1133bb853b5cfaa063",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Духовка",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 2,
        "__v": 0
    },
    {
        "_id": "5cebcc1833bb853b5cfaa064",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Микроволновка",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 3,
        "__v": 0
    },
    {
        "_id": "5cebcc2133bb853b5cfaa065",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Кухонный шкаф",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 4,
        "__v": 0
    },
    {
        "_id": "5cebcc2a33bb853b5cfaa066",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Глажка одежды",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 5,
        "__v": 0
    },
    {
        "_id": "5cebcc3233bb853b5cfaa067",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Помыть посуду",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 6,
        "__v": 0
    },
    {
        "_id": "5cebcc3933bb853b5cfaa068",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Гардероб",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 7,
        "__v": 0
    },
    {
        "_id": "5cebcc4033bb853b5cfaa069",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Мытье окон",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 8,
        "__v": 0
    },
    {
        "_id": "5cebcc4833bb853b5cfaa06a",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Люстра",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 9,
        "__v": 0
    },
    {
        "_id": "5cebcc5033bb853b5cfaa06b",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Пароочиститель",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 10,
        "__v": 0
    },
    {
        "_id": "5cebcc5733bb853b5cfaa06c",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Забрать ключи",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 11,
        "__v": 0
    },
    {
        "_id": "5cebcc6033bb853b5cfaa06d",
        "order": "Вы можете выбрать дополнительные услуги:",
        "text": "Вернуть ключи",
        "icon": "d6a524763dd8d4b49a6e4548a79ad408es-card-icon.png",
        "price": 5000,
        "discount": 0,
        "name": "additional_services",
        "kind": "Counter",
        "position": 12,
        "__v": 0
    }
];



schema = new OrderSchema(items)
schema.convert()